In [ ]:
// Question 2

In [ ]:
import numpy as np

# Set the random seed
np.random.seed(47)

# Create a 5x5 matrix A with random integer entries between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original matrix A:")
print(A)

# Reduce matrix A to its row echelon form
rows, cols = A.shape
current_row = 0

for col in range(cols):
    # Find the first non-zero element in the column
    non_zero_row = current_row
    while non_zero_row < rows and A[non_zero_row, col] == 0:
        non_zero_row += 1

    if non_zero_row == rows:
        # This column is all zeros below current_row, move to the next column
        continue

    # Swap rows so that the non-zero element is in the current row
    A[current_row], A[non_zero_row] = A[non_zero_row], A[current_row]

    # Normalize the current row
    A[current_row] = A[current_row] / A[current_row, col]

    # Eliminate non-zero elements below the pivot
    for i in range(current_row + 1, rows):
        A[i] -= A[current_row] * A[i, col]

    current_row += 1

print("\nRow echelon form of matrix A:")
print(A)


Original matrix A:
[[7 6 7 8 8]
 [3 0 7 0 7]
 [7 1 7 2 2]
 [1 7 4 8 9]
 [2 9 1 5 0]]

Row echelon form of matrix A:
[[ 1  0  1  1  1]
 [ 0  1  0 -5 -5]
 [ 0  0  1 14 14]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]]
