In [ ]:
// Question 3

In [ ]:
import numpy as np

# Given matrix A (previously obtained)
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

# Perform Singular Value Decomposition (SVD)
U, Sigma, Vt = np.linalg.svd(A)

# Create the diagonal matrix Σ from the 1-D array Sigma
Sigma_mat = np.diag(Sigma)

# Print matrices U, Σ, and Vᵀ
print("Matrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma_mat)
print("\nMatrix Vᵀ:")
print(Vt)

# Verify that A equals the product of U, Σ, and Vᵀ
A_reconstructed = np.dot(U, np.dot(Sigma_mat, Vt))
print("\nMatrix A reconstructed from SVD:")
print(A_reconstructed)

# Find the rank-2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(Sigma_mat[:2, :2], Vt[:2, :]))
print("\nRank-2 approximation of matrix A:")
print(rank_2_approximation)

# Find the rank-3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(Sigma_mat[:3, :3], Vt[:3, :]))
print("\nRank-3 approximation of matrix A:")
print(rank_3_approximation)


Matrix U:
[[-0.09359323 -0.76892152  0.61130515  0.0196316  -0.16099879]
 [-0.24363203 -0.49055421 -0.5142169  -0.45682855  0.4763283 ]
 [-0.39367083 -0.2121869  -0.3594458   0.81870773 -0.02272392]
 [-0.54370962  0.06618041 -0.18367831 -0.34545623 -0.73954194]
 [-0.69374842  0.34454772  0.44603585 -0.03605456  0.44693633]]

Matrix Σ:
[[7.42540539e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 3.36681954e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.98266488e-15 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.53916447e-15
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.08136977e-16]]

Matrix Vᵀ:
[[-0.39262281 -0.41913118 -0.44563955 -0.47214793 -0.4986563 ]
 [ 0.667718    0.35260325  0.0374885  -0.27762625 -0.592741  ]
 [ 0.5359956  -0.50603463 -0.52349916  0.42111979  0.0724184 ]
 [-0.33541664  0.36000724 -0.21070021  0.68304527 -0.49693566